Merge branch 'main' into percentage
progwise/emotionalTerritories pull request #20
Opened 2023-11-11 22:52 UTC by splendidcomputer

2023-11-11 22:52 UTC, splendidcomputer commented
Fix: adds showing < 5% for small percentages.

2023-11-13 07:41 UTC, moncapitaine commented on apps/web/app/cluster.tsx
> +              {cluster.percentage >= 5 ? cluster.percentage.toFixed(1) : "<5"} %
use template strings ?

2023-11-13 07:42 UTC, moncapitaine requested changes
can you create the string more readable?

2023-11-13 07:42 UTC, moncapitaine commented
and please resolve conflicts

2023-11-14 07:14 UTC, closed without merging