Adds Minkowski norm, and the other linkage methods.
progwise/emotionalTerritories pull request #42
Opened 2023-11-22 09:04 UTC by splendidcomputer

Adds the Minkowski norm (to calcualte the pointwise distances), as well as the Minimum and Complete linkage methods (to calcualte the inter-cluster distances).

2023-11-22 09:19 UTC, moncapitaine requested changes
please describe what you did. the name Merge branch... is not a valid PR name

2023-11-22 10:36 UTC, splendidcomputer commented on README.md
Modified the README to make it customized according to the Emotional Territories project.

2023-11-22 10:36 UTC, splendidcomputer commented on apps/cli/src/FindClosestPair.ts
This function has been renamed to findClosestPair.ts

2023-11-24 17:52 UTC, moncapitaine approved these changes

2023-11-24 17:56 UTC, merged